apiVersion: v1
kind: Service
metadata:
  name: workbridge-backend-service
spec:
  selector:
    app: workbridge-backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      # Assign a static port for easy access
      nodePort: 30008