apiVersion: apps/v1
kind: Deployment
metadata:
  name: workbridge-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workbridge-backend
  template:
    metadata:
      labels:
        app: workbridge-backend
    spec:
      containers:
      - name: backend
        image: shai3600/workbridge-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://workbridgeuser:your-strong-password@postgres-service:5432/workbridgedb"
        - name: ALLOWED_ORIGINS
          value: "http://localhost:30007"