apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: workbridge
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: workbridge

  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_HOST: postgres      
  DB_PORT: "5432"
  DB_NAME: workbridge


  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/workbridge
