from fastapi import APIRouter, HTTPException, Header,Depends
from sqlalchemy.orm import Session
from db.database import SessionLocal
from schemas.user import UserRegister, UserLogin, UserCreate, UserUpdate, UserOut
from utils.auth import hash_password, verify_password
from utils.auth_token import decode_access_token, create_access_token
from utils.db_user import get_user_by_email_db, create_user_db, user_exists_db

import logging

logger = logging.getLogger(__name__)

router = APIRouter()

def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

@router.post("/register", status_code=201)
async def register(user: UserRegister, db: Session = Depends(get_db)):
    logger.info("Received registration request for email: %s", user.email)

    existing_user = get_user_by_email_db(db,user.email)
    if existing_user:
        logger.warning("Registration failed: email already exists: %s", user.email)
        raise HTTPException(status_code=400, detail="Email already exists")

    logger.debug("Email is unique. Proceeding to hash password.")
    hashed_password = hash_password(user.password)

    logger.debug("Password hashed for email: %s", user.email)
    user_data = UserCreate(
        email = user.email,
        hashed_password = hashed_password,
        first_name = user.first_name,
        last_name = user.last_name,
    )
    create_user_db(db,user_data)
    logger.info("User successfully created in database: %s", user.email)

    token = create_access_token({"sub": user.email})
    return {"access_token": token, "token_type": "bearer"}


@router.post("/login")
async def login(user: UserLogin, db: Session = Depends(get_db)):
    logger.info("Login attempt for email: %s", user.email)

    db_user = get_user_by_email_db(db, user.email)
    if not db_user:
        raise HTTPException(status_code=400, detail="Invalid credentials")
    if not verify_password(user.password, db_user.hashed_password):
        raise HTTPException(status_code=400, detail="Invalid credentials")
    token = create_access_token({"sub": user.email})
    logger.debug("Access token created for email: %s", user.email)

    return {"access_token": token, "token_type": "bearer"}

@router.get("/me", response_model=UserOut)
async def get_me(authorization: str = Header(...), db: Session = Depends(get_db)):
    """
    This endpoint expects an Authorization header in the format:
    "Authorization: Bearer <JWT token>"
    The token is used to authenticate the user without using server-side sessions.
    """

    logger.info("Accessing /me endpoint")

    if not authorization.startswith("Bearer "):
        logger.warning("Invalid authorization header format: %s", authorization)
        raise HTTPException(status_code=400, detail="Invalid authorization header")

    token = authorization.split(" ")[1]
    payload = decode_access_token(token)
    email = payload.get("sub")
    if not email:
        raise HTTPException(status_code=401, detail="Invalid token")

    user = get_user_by_email_db(db, email)
    if not user:
        raise HTTPException(status_code=404, detail="User not found")

    return user

@router.put("/me", response_model=UserOut)
async def update_me(update: UserUpdate, authorization: str = Header(...), db: Session = Depends(get_db)):
    """
    Partial profile update. Only fields provided in the payload are updated.
    display_name is generated by DB and cannot be directly edited.
    """
    logger.info("Accessing /me (PUT) for profile update")

    if not authorization.startswith("Bearer "):
        logger.warning("Invalid authorization header format for PUT /me: %s", authorization)
        raise HTTPException(status_code=400, detail="Invalid authorization header")

    token = authorization.split(" ")[1]
    payload = decode_access_token(token)
    email = payload.get("sub")
    if not email:
        raise HTTPException(status_code=401, detail="Invalid token")

    user = get_user_by_email_db(db, email)
    if not user:
        raise HTTPException(status_code=404, detail="User not found")

    # Update only provided fields
    if update.first_name is not None:
        user.first_name = update.first_name
    if update.last_name is not None:
        user.last_name = update.last_name
    if update.avatar_url is not None:
        user.avatar_url = str(update.avatar_url)
    if update.bio is not None:
        user.bio = update.bio
    if update.job_title is not None:
        user.job_title = update.job_title

    db.add(user)
    db.commit()
    db.refresh(user)  # ensures display_name recomputed is visible

    logger.info("Profile updated for user: %s", email)
    return user


@router.get("/users/exists/{email}")
async def check_user_exists(email: str, db: Session = Depends(get_db)):
    """
    Check if a user with the given email address exists in the database.
    """
    logger.info(f"Checking if user exists: {email}")
    user_exists = user_exists_db(db, email)
    return {"exists": user_exists}
